version: 1
update_configs:
  # Dependencies
  - package_manager: javascript
    directory: /
    update_schedule: live
    default_assignees:
      - franky47
    automerged_updates:
      - match:
          dependency_type: development
          update_type: all
      - match:
          dependency_type: production
          update_type: in_range
      - match:
          dependency_type: production
          update_type: security:patch
  # GitHub Actions
  - package_manager: github_actions
    directory: /
    update_schedule: weekly
    default_reviewers:
      - franky47
    default_assignees:
      - franky47
